<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <BasinPlatforms>linux;macos;windows</BasinPlatforms>
    <PackageId>Basin.UI.Decoration</PackageId>
    <RootNamespace>Basin.UI.Decoration</RootNamespace>
    <Description>Shared UI elements for Basin.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Basin.Core/Basin.Core.csproj" />
    <ProjectReference Include="../Basin.Scene/Basin.Scene.csproj" />
  </ItemGroup>

</Project>
