<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Inlet</RootNamespace>
    <AssemblyName>inlet</AssemblyName>
    <IsPackable>false</IsPackable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ServerGarbageCollection>false</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Basin.Cli/Basin.Cli.csproj" />
    <ProjectReference Include="../../src/Basin.Core/Basin.Core.csproj" />
    <ProjectReference Include="../../src/Basin.Backend.Headless/Basin.Backend.Headless.csproj" />
    <ProjectReference Include="../../src/Basin.Backend.Wayland/Basin.Backend.Wayland.csproj" />
    <ProjectReference Include="../../src/Basin.Renderers/Basin.Renderers.csproj" />
    <ProjectReference Include="../../src/Basin.Scene/Basin.Scene.csproj" />
    <ProjectReference Include="../../src/Basin.Seat/Basin.Seat.csproj" />
    <ProjectReference Include="../../src/Basin.Seat.Backends/Basin.Seat.Backends.csproj" />
    <ProjectReference Include="../../src/Basin.Desktop/Basin.Desktop.csproj" />
    <ProjectReference Include="../../src/Basin.Shell.Xdg/Basin.Shell.Xdg.csproj" />
    <ProjectReference Include="../../src/Basin.Shell.River/Basin.Shell.River.csproj" />
    <ProjectReference Include="../../src/Basin.XWayland/Basin.XWayland.csproj" />
    <ProjectReference Include="../../src/Basin.Backend.Drm/Basin.Backend.Drm.csproj" />
    <ProjectReference Include="../../src/Basin.Backend.Libinput/Basin.Backend.Libinput.csproj" />
    <ProjectReference Include="../../src/Basin.Session/Basin.Session.csproj" />
    <ProjectReference Include="../../src/Basin.Color/Basin.Color.csproj" />
    <ProjectReference Include="../../src/Basin.Host/Basin.Host.csproj" />
  </ItemGroup>


</Project>
