<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <BasinPlatforms>linux;macos;windows</BasinPlatforms>
    <PackageId>Basin.UI.Skia</PackageId>
    <RootNamespace>Basin.UI.Skia</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);NU5104</NoWarn>
    <Description>Skia UI adapter for Basin, used to draw UI elements.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Basin.Core/Basin.Core.csproj" />
    <ProjectReference Include="../Basin.Render.Skia/Basin.Render.Skia.csproj" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.HarfBuzz" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Condition="$([MSBuild]::IsOSPlatform('Linux'))" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Condition="$([MSBuild]::IsOSPlatform('Linux'))" />
  </ItemGroup>

</Project>
