using Prowl.PaperUI;

namespace Basin.UI.Paper;

public static class EvdevPaperKeys
{
    private static readonly PaperKey[] Table = Build();

    public static PaperKey KeyOf(uint key) => key < (uint)Table.Length ? Table[key] : PaperKey.Unknown;

    private static PaperKey[] Build()
    {
        var table = new PaperKey[256];
        table[1] = PaperKey.Escape;
        table[2] = PaperKey.Num1;
        table[3] = PaperKey.Num2;
        table[4] = PaperKey.Num3;
        table[5] = PaperKey.Num4;
        table[6] = PaperKey.Num5;
        table[7] = PaperKey.Num6;
        table[8] = PaperKey.Num7;
        table[9] = PaperKey.Num8;
        table[10] = PaperKey.Num9;
        table[11] = PaperKey.Num0;
        table[12] = PaperKey.Minus;
        table[13] = PaperKey.Equals;
        table[14] = PaperKey.Backspace;
        table[15] = PaperKey.Tab;
        table[16] = PaperKey.Q;
        table[17] = PaperKey.W;
        table[18] = PaperKey.E;
        table[19] = PaperKey.R;
        table[20] = PaperKey.T;
        table[21] = PaperKey.Y;
        table[22] = PaperKey.U;
        table[23] = PaperKey.I;
        table[24] = PaperKey.O;
        table[25] = PaperKey.P;
        table[26] = PaperKey.LeftBracket;
        table[27] = PaperKey.RightBracket;
        table[28] = PaperKey.Enter;
        table[29] = PaperKey.LeftControl;
        table[30] = PaperKey.A;
        table[31] = PaperKey.S;
        table[32] = PaperKey.D;
        table[33] = PaperKey.F;
        table[34] = PaperKey.G;
        table[35] = PaperKey.H;
        table[36] = PaperKey.J;
        table[37] = PaperKey.K;
        table[38] = PaperKey.L;
        table[39] = PaperKey.Semicolon;
        table[40] = PaperKey.Apostrophe;
        table[41] = PaperKey.Grave;
        table[42] = PaperKey.LeftShift;
        table[43] = PaperKey.Backslash;
        table[44] = PaperKey.Z;
        table[45] = PaperKey.X;
        table[46] = PaperKey.C;
        table[47] = PaperKey.V;
        table[48] = PaperKey.B;
        table[49] = PaperKey.N;
        table[50] = PaperKey.M;
        table[51] = PaperKey.Comma;
        table[52] = PaperKey.Period;
        table[53] = PaperKey.Slash;
        table[54] = PaperKey.RightShift;
        table[55] = PaperKey.KeypadMultiply;
        table[56] = PaperKey.LeftAlt;
        table[57] = PaperKey.Space;
        table[58] = PaperKey.CapsLock;
        table[59] = PaperKey.F1;
        table[60] = PaperKey.F2;
        table[61] = PaperKey.F3;
        table[62] = PaperKey.F4;
        table[63] = PaperKey.F5;
        table[64] = PaperKey.F6;
        table[65] = PaperKey.F7;
        table[66] = PaperKey.F8;
        table[67] = PaperKey.F9;
        table[68] = PaperKey.F10;
        table[69] = PaperKey.NumLock;
        table[70] = PaperKey.ScrollLock;
        table[71] = PaperKey.Keypad7;
        table[72] = PaperKey.Keypad8;
        table[73] = PaperKey.Keypad9;
        table[74] = PaperKey.KeypadMinus;
        table[75] = PaperKey.Keypad4;
        table[76] = PaperKey.Keypad5;
        table[77] = PaperKey.Keypad6;
        table[78] = PaperKey.KeypadPlus;
        table[79] = PaperKey.Keypad1;
        table[80] = PaperKey.Keypad2;
        table[81] = PaperKey.Keypad3;
        table[82] = PaperKey.Keypad0;
        table[83] = PaperKey.KeypadDecimal;
        table[87] = PaperKey.F11;
        table[88] = PaperKey.F12;
        table[96] = PaperKey.KeypadEnter;
        table[97] = PaperKey.RightControl;
        table[98] = PaperKey.KeypadDivide;
        table[99] = PaperKey.PrintScreen;
        table[100] = PaperKey.RightAlt;
        table[102] = PaperKey.Home;
        table[103] = PaperKey.Up;
        table[104] = PaperKey.PageUp;
        table[105] = PaperKey.Left;
        table[106] = PaperKey.Right;
        table[107] = PaperKey.End;
        table[108] = PaperKey.Down;
        table[109] = PaperKey.PageDown;
        table[110] = PaperKey.Insert;
        table[111] = PaperKey.Delete;
        table[113] = PaperKey.AudioMute;
        table[117] = PaperKey.KeypadEquals;
        table[119] = PaperKey.Pause;
        table[125] = PaperKey.LeftSuper;
        table[126] = PaperKey.RightSuper;
        table[127] = PaperKey.Menu;
        table[138] = PaperKey.Help;
        table[163] = PaperKey.AudioNext;
        table[164] = PaperKey.AudioPlay;
        table[165] = PaperKey.AudioPrevious;
        table[166] = PaperKey.AudioStop;
        return table;
    }
}
