<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Basin.Rashader</PackageId>
    <RootNamespace>Basin.Rashader</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Description>librashader preset loading for Basin.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Basin.Core/Basin.Core.csproj" />
    <InternalsVisibleTo Include="Basin.Rashader.Gl" />
    <InternalsVisibleTo Include="Basin.Rashader.Vulkan" />
    <InternalsVisibleTo Include="Basin.Tests" />
  </ItemGroup>

</Project>
