<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Dinghy</RootNamespace>
    <AssemblyName>dinghy</AssemblyName>
    <IsPackable>false</IsPackable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <NoWarn>$(NoWarn);IL2104</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Basin.Cli/Basin.Cli.csproj" />
    <ProjectReference Include="../../src/Basin.WindowManager/Basin.WindowManager.csproj" />
    <ProjectReference Include="../../src/Basin.WindowManager.Skia/Basin.WindowManager.Skia.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" />
    <PackageReference Include="Tomlyn" />
    <PackageReference Include="SkiaSharp.HarfBuzz" />
  </ItemGroup>

</Project>
