<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <BasinPlatforms>linux;macos;windows</BasinPlatforms>
    <PackageId>Basin.Seat</PackageId>
    <RootNamespace>Basin.Seat</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Description>Seat mechanism for Basin.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Basin.Core/Basin.Core.csproj" />
    <PackageReference Include="xkbcommon-dotnet" />
  </ItemGroup>

</Project>
