using Avalonia.Input;
using Basin.Diagnostics;

namespace Basin.Avalonia;

internal static class AvaloniaKeyMap
{
    public const uint BtnLeft = 0x110;
    public const uint BtnRight = 0x111;
    public const uint BtnMiddle = 0x112;
    public const uint BtnSide = 0x113;
    public const uint BtnExtra = 0x114;

    public static uint ButtonFor(PointerUpdateKind kind) => kind switch
    {
        PointerUpdateKind.LeftButtonPressed or PointerUpdateKind.LeftButtonReleased => BtnLeft,
        PointerUpdateKind.RightButtonPressed or PointerUpdateKind.RightButtonReleased => BtnRight,
        PointerUpdateKind.MiddleButtonPressed or PointerUpdateKind.MiddleButtonReleased => BtnMiddle,
        PointerUpdateKind.XButton1Pressed or PointerUpdateKind.XButton1Released => BtnSide,
        PointerUpdateKind.XButton2Pressed or PointerUpdateKind.XButton2Released => BtnExtra,
        _ => 0,
    };

    public static uint EvdevFor(PhysicalKey key) => key switch
    {
        PhysicalKey.Escape => 1,
        PhysicalKey.Digit1 => 2,
        PhysicalKey.Digit2 => 3,
        PhysicalKey.Digit3 => 4,
        PhysicalKey.Digit4 => 5,
        PhysicalKey.Digit5 => 6,
        PhysicalKey.Digit6 => 7,
        PhysicalKey.Digit7 => 8,
        PhysicalKey.Digit8 => 9,
        PhysicalKey.Digit9 => 10,
        PhysicalKey.Digit0 => 11,
        PhysicalKey.Minus => 12,
        PhysicalKey.Equal => 13,
        PhysicalKey.Backspace => 14,
        PhysicalKey.Tab => 15,
        PhysicalKey.Q => 16,
        PhysicalKey.W => 17,
        PhysicalKey.E => 18,
        PhysicalKey.R => 19,
        PhysicalKey.T => 20,
        PhysicalKey.Y => 21,
        PhysicalKey.U => 22,
        PhysicalKey.I => 23,
        PhysicalKey.O => 24,
        PhysicalKey.P => 25,
        PhysicalKey.BracketLeft => 26,
        PhysicalKey.BracketRight => 27,
        PhysicalKey.Enter => 28,
        PhysicalKey.ControlLeft => 29,
        PhysicalKey.A => 30,
        PhysicalKey.S => 31,
        PhysicalKey.D => 32,
        PhysicalKey.F => 33,
        PhysicalKey.G => 34,
        PhysicalKey.H => 35,
        PhysicalKey.J => 36,
        PhysicalKey.K => 37,
        PhysicalKey.L => 38,
        PhysicalKey.Semicolon => 39,
        PhysicalKey.Quote => 40,
        PhysicalKey.Backquote => 41,
        PhysicalKey.ShiftLeft => 42,
        PhysicalKey.Backslash => 43,
        PhysicalKey.Z => 44,
        PhysicalKey.X => 45,
        PhysicalKey.C => 46,
        PhysicalKey.V => 47,
        PhysicalKey.B => 48,
        PhysicalKey.N => 49,
        PhysicalKey.M => 50,
        PhysicalKey.Comma => 51,
        PhysicalKey.Period => 52,
        PhysicalKey.Slash => 53,
        PhysicalKey.ShiftRight => 54,
        PhysicalKey.NumPadMultiply => 55,
        PhysicalKey.AltLeft => 56,
        PhysicalKey.Space => 57,
        PhysicalKey.CapsLock => 58,
        PhysicalKey.F1 => 59,
        PhysicalKey.F2 => 60,
        PhysicalKey.F3 => 61,
        PhysicalKey.F4 => 62,
        PhysicalKey.F5 => 63,
        PhysicalKey.F6 => 64,
        PhysicalKey.F7 => 65,
        PhysicalKey.F8 => 66,
        PhysicalKey.F9 => 67,
        PhysicalKey.F10 => 68,
        PhysicalKey.NumLock => 69,
        PhysicalKey.ScrollLock => 70,
        PhysicalKey.NumPad7 => 71,
        PhysicalKey.NumPad8 => 72,
        PhysicalKey.NumPad9 => 73,
        PhysicalKey.NumPadSubtract => 74,
        PhysicalKey.NumPad4 => 75,
        PhysicalKey.NumPad5 => 76,
        PhysicalKey.NumPad6 => 77,
        PhysicalKey.NumPadAdd => 78,
        PhysicalKey.NumPad1 => 79,
        PhysicalKey.NumPad2 => 80,
        PhysicalKey.NumPad3 => 81,
        PhysicalKey.NumPad0 => 82,
        PhysicalKey.NumPadDecimal => 83,
        PhysicalKey.IntlBackslash => 86,
        PhysicalKey.F11 => 87,
        PhysicalKey.F12 => 88,
        PhysicalKey.IntlRo => 89,
        PhysicalKey.Convert => 92,
        PhysicalKey.KanaMode => 93,
        PhysicalKey.NonConvert => 94,
        PhysicalKey.NumPadEnter => 96,
        PhysicalKey.ControlRight => 97,
        PhysicalKey.NumPadDivide => 98,
        PhysicalKey.PrintScreen => 99,
        PhysicalKey.AltRight => 100,
        PhysicalKey.Home => 102,
        PhysicalKey.ArrowUp => 103,
        PhysicalKey.PageUp => 104,
        PhysicalKey.ArrowLeft => 105,
        PhysicalKey.ArrowRight => 106,
        PhysicalKey.End => 107,
        PhysicalKey.ArrowDown => 108,
        PhysicalKey.PageDown => 109,
        PhysicalKey.Insert => 110,
        PhysicalKey.Delete => 111,
        PhysicalKey.AudioVolumeMute => 113,
        PhysicalKey.AudioVolumeDown => 114,
        PhysicalKey.AudioVolumeUp => 115,
        PhysicalKey.NumPadEqual => 117,
        PhysicalKey.Pause => 119,
        PhysicalKey.NumPadComma => 121,
        PhysicalKey.Lang1 => 122,
        PhysicalKey.Lang2 => 123,
        PhysicalKey.IntlYen => 124,
        PhysicalKey.MetaLeft => 125,
        PhysicalKey.MetaRight => 126,
        PhysicalKey.ContextMenu => 127,
        _ => 0,
    };
}
