using System.Text.Json;
using System.Text.Json.Serialization;

namespace Basin.Ipc;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
    RespectRequiredConstructorParameters = true)]
[JsonSerializable(typeof(IpcApprovalAnswerParams))]
[JsonSerializable(typeof(IpcApprovalRequested))]
[JsonSerializable(typeof(IpcAxisParams))]
[JsonSerializable(typeof(IpcBox))]
[JsonSerializable(typeof(IpcButton))]
[JsonSerializable(typeof(IpcCaptureOutputParams))]
[JsonSerializable(typeof(IpcCaptureRegionParams))]
[JsonSerializable(typeof(IpcCaptureResult))]
[JsonSerializable(typeof(IpcCaptureTo))]
[JsonSerializable(typeof(IpcCaptureWindowParams))]
[JsonSerializable(typeof(IpcChordParams))]
[JsonSerializable(typeof(IpcChordResult))]
[JsonSerializable(typeof(IpcClipboardChanged))]
[JsonSerializable(typeof(IpcClipboard))]
[JsonSerializable(typeof(IpcClipboardParams))]
[JsonSerializable(typeof(IpcClipboardWriteParams))]
[JsonSerializable(typeof(IpcEmpty))]
[JsonSerializable(typeof(IpcErrorBody))]
[JsonSerializable(typeof(IpcEventList))]
[JsonSerializable(typeof(IpcEventsParams))]
[JsonSerializable(typeof(IpcIdleInhibited))]
[JsonSerializable(typeof(IpcIdleStatus))]
[JsonSerializable(typeof(IpcIdleToken))]
[JsonSerializable(typeof(IpcIdParams))]
[JsonSerializable(typeof(IpcKeymapInfo))]
[JsonSerializable(typeof(IpcKeymapParams))]
[JsonSerializable(typeof(IpcKeyParams))]
[JsonSerializable(typeof(IpcLineReply))]
[JsonSerializable(typeof(IpcLockStatus))]
[JsonSerializable(typeof(IpcMethodDetail))]
[JsonSerializable(typeof(IpcMethodDetailList))]
[JsonSerializable(typeof(IpcMethodList))]
[JsonSerializable(typeof(IpcMethodsParams))]
[JsonSerializable(typeof(IpcModeChange))]
[JsonSerializable(typeof(IpcMoveParams))]
[JsonSerializable(typeof(IpcOutputChange))]
[JsonSerializable(typeof(IpcOptionalBox))]
[JsonSerializable(typeof(IpcOutput))]
[JsonSerializable(typeof(IpcOutputList))]
[JsonSerializable(typeof(IpcOutputMode))]
[JsonSerializable(typeof(IpcOutputPowerChanged))]
[JsonSerializable(typeof(IpcOutputsParams))]
[JsonSerializable(typeof(IpcOutputTestResult))]
[JsonSerializable(typeof(IpcPoint))]
[JsonSerializable(typeof(IpcPointerButtonParams))]
[JsonSerializable(typeof(IpcPointerMoveParams))]
[JsonSerializable(typeof(IpcPowerParams))]
[JsonSerializable(typeof(IpcRawJson))]
[JsonSerializable(typeof(IpcResizeParams))]
[JsonSerializable(typeof(IpcSendToOutputParams))]
[JsonSerializable(typeof(IpcSendToWorkspaceParams))]
[JsonSerializable(typeof(IpcSessionDescription))]
[JsonSerializable(typeof(IpcSetStateParams))]
[JsonSerializable(typeof(IpcShortcutActivated))]
[JsonSerializable(typeof(IpcSize))]
[JsonSerializable(typeof(IpcSpawnParams))]
[JsonSerializable(typeof(IpcProcess))]
[JsonSerializable(typeof(IpcProcessList))]
[JsonSerializable(typeof(IpcProcessExited))]
[JsonSerializable(typeof(IpcProcessLog))]
[JsonSerializable(typeof(IpcProcessKillParams))]
[JsonSerializable(typeof(IpcProcessLogParams))]
[JsonSerializable(typeof(IpcSpawnResult))]
[JsonSerializable(typeof(IpcStack))]
[JsonSerializable(typeof(IpcTextParams))]
[JsonSerializable(typeof(IpcTextResult))]
[JsonSerializable(typeof(IpcTokenParams))]
[JsonSerializable(typeof(IpcTouchParams))]
[JsonSerializable(typeof(IpcVersion))]
[JsonSerializable(typeof(IpcWaitParams))]
[JsonSerializable(typeof(IpcWaitIdleParams))]
[JsonSerializable(typeof(IpcWaitIdleResult))]
[JsonSerializable(typeof(IpcWindow))]
[JsonSerializable(typeof(IpcWindowId))]
[JsonSerializable(typeof(IpcWindowList))]
[JsonSerializable(typeof(IpcWindowState))]
[JsonSerializable(typeof(IpcWorkspaceCreateParams))]
[JsonSerializable(typeof(IpcWorkspace))]
[JsonSerializable(typeof(IpcWorkspaceGroup))]
[JsonSerializable(typeof(IpcWorkspaceList))]
[JsonSerializable(typeof(IpcWorkspaceMoveParams))]
[JsonSerializable(typeof(JsonElement))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(Dictionary<string, JsonElement>))]
public sealed partial class IpcJsonContext : JsonSerializerContext
{
}
