<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Basin.Cli</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Basin.Core/Basin.Core.csproj" />
    <ProjectReference Include="../Basin.Config/Basin.Config.csproj" />
    <ProjectReference Include="../Basin.Freedesktop/Basin.Freedesktop.csproj" />
    <ProjectReference Include="../Basin.Ipc/Basin.Ipc.csproj" />
  </ItemGroup>

</Project>
