<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Basin.Color</PackageId>
    <RootNamespace>Basin.Color</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Description>Color mechanism for Basin.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Basin.Core/Basin.Core.csproj" />
    <PackageReference Include="lcms2-dotnet" />
  </ItemGroup>

</Project>
