<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Basin.Effects</PackageId>
    <RootNamespace>Basin.Effects</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Description>Reference visual effects for Basin.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Basin.Core/Basin.Core.csproj" />
    <ProjectReference Include="../Basin.Scene/Basin.Scene.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="shaders/fire.frag.spv" LogicalName="fire.frag.spv" />
  </ItemGroup>

</Project>
